Update to SudokuFuncs.py file
Raj-Srikar/Sudoku-Solver pull request #1
Opened 2021-12-08 13:33 UTC by HASH-0021

I made changes to some functions in 'SudokuFuncs.py' file. @Raj-Srikar, amend the changes accordingly.

2021-12-10 11:52 UTC, Raj-Srikar commented on SudokuFuncs.py
>      return_list.clear()
```suggestion
    return_list = []
```

2021-12-10 12:39 UTC, Raj-Srikar requested changes
Looks Great 🔥! Address the suggestions I've made and update the changes accordingly. @HASH-0021

2021-12-10 12:39 UTC, Raj-Srikar commented on SudokuFuncs.py
>      return_list.clear()
```suggestion
```

2021-12-10 12:39 UTC, Raj-Srikar commented on SudokuFuncs.py
>  return_list = []        #Global declaration of the List to be returned after all the combinations are appended to it
```suggestion
```

2021-12-10 12:39 UTC, Raj-Srikar commented on SudokuFuncs.py
>      return return_list
```suggestion
    return list(map(lambda x: list(x), permutations(li)))
```
Edit the Docstring accordingly.

2021-12-10 12:39 UTC, Raj-Srikar commented on SudokuFuncs.py
> +import itertools
```suggestion
from itertools import permutations
```

2021-12-10 12:39 UTC, Raj-Srikar commented on SudokuFuncs.py
>      return li_dif
```suggestion
    return [i for i in li1 + li2 if i in li1 and i not in li2]
```
Let's not waste memory by specifically allocating the list to a variable and then returning it ;)
Make changes for any other similar snippets in the program, if found.

2021-12-10 12:39 UTC, Raj-Srikar commented on SudokuFuncs.py
>      (Any one of the arguments 'fileName' and 'matrix' should be given. Else rises ValueError)
```suggestion
    taking the matrix as a variable and either shows the solution or returns it. Can also tell the execution time
    (Any one of the arguments 'fileName' or 'matrix' should be given. Else rises ValueError)
```

2021-12-10 12:39 UTC, Raj-Srikar commented on SudokuFuncs.py
>      Solves a Sudoku by prompting about sudoku or reading a text file containing the sudoku or by directly
```suggestion
    Solves a Sudoku by prompting the sudoku or reading a text file containing the sudoku or by directly
```

2021-12-11 07:56 UTC, HASH-0021 reviewed
Changed the docstrings for the 'all_combinations' function. No other changes found that are containing little-to-no-use variables or functions in 'SudokuFuncs.py' file. @Raj-Srikar, review this change and merge the pull request if everything is fine.

2021-12-11 07:56 UTC, HASH-0021 commented on SudokuFuncs.py
> +    This will append all combination lists to the list, 'return_list'
```suggestion
    This will return a list containing all combination lists
```

2021-12-12 07:56 UTC, Raj-Srikar requested changes

2021-12-12 07:56 UTC, Raj-Srikar commented on SudokuFuncs.py
>      returns: list, 'return_list' which contains lists of all the possible combinations of 'li' list
```suggestion
    returns: a list, which contains lists of all the possible combinations of 'li' list
```

2021-12-12 08:07 UTC, merged

2021-12-12 08:08 UTC, Raj-Srikar commented
All good! Congrats on the first merged pull request. 🎉